version: "3.7"

services:
  zssn-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: zssn-api
    volumes:
      - .:/usr/app
    expose:
      - "${PORT:-3030}"
    ports:
      - "${PORT:-3030}:${PORT:-3030}"
      - "9229:9229"
    command: yarn start:dev
    depends_on:
      - mongo
  mongo-express:
    image: mongo-express
    ports:
      - ${MONGO_EXPRESS_PORT:-5555}:8081
    environment:
      ME_CONFIG_MONGODB_PORT: ${DB_PORT:-27017}
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGODB_ADMINUSERNAME:-root}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGODB_ADMINPASSWORD:-secret}
    depends_on:
      - mongo
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_ADMINUSERNAME:-root}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_ADMINPASSWORD:-secret}
    ports:
      - "${DB_PORT:-27017}:${DB_PORT:-27017}"
    volumes:
      - mongo-data:/data/db
  
volumes:
  mongo-data: