version: "3.7"

services:
  zssn-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: zssn-api
    volumes:
      - .:/usr/app
    expose:
      - "3030"
    ports:
      - "3030:3030"
      - "9229:9229"
    command: yarn start:dev
    depends_on:
      - mongo
  mongo-express:
    image: mongo-express
    ports:
      - 5555:8081
    environment:
      #ME_CONFIG_BASICAUTH_USERNAME: vittis
      #ME_CONFIG_BASICAUTH_PASSWORD: secret
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: secret
    depends_on:
      - mongo
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
  
volumes:
  mongo-data: